services:
  - type: web
    name: baristaapp
    env: python
    buildCommand: ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DB_SQL_SERVER_GIG
        sync: false
